language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
    - export PHPCS_GITHUB_SRC=squizlabs/PHP_CodeSniffer
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPCS_BRANCH=master
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $(pwd)

script:
    - ant travis

branches:
  except:
    - jenkins

notifications:
  email:
    - dev@escapestudios.com
